[build]
  command = "npx prisma generate && npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@nestjs/microservices", 
    "pg-native", 
    "@nestjs/websockets",
    "@nestjs/mongoose",
    "@mikro-orm/core",
    "@nestjs/sequelize",
    "@nestjs/typeorm",
    "@bull-board/nestjs",
    "@bull-board/express",
    "@bull-board/api"
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
